### PR TITLE
Remove vendor dir and add golang-check.v1-dev to control

### PR DESCRIPTION
**Pull request by openarun**
This fix makes the use of gopkg.in/check.v1 golang package from golang-check.v1-dev debian package.
Removes unwanted vendor directory.

### CODE REVIEW

**Comment by BLumia** [comment]
The CLA still needs to be signed if you don't mind (see https://github.com/linuxdeepin/go-gir-generator/pull/12#issuecomment-1220145160). I can do the rest about ensure the commit message follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) guideline :)

**Comment by openarun** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by openarun** [comment]
recheck

**Review by dengbo11 — APPROVED** [review]

**Review by BLumia — APPROVED** [review]

**Pull request merged**
